{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "4d771b06",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import psycopg2\n",
    "import dlt\n",
    "from dlt.sources.helpers.rest_client import RESTClient\n",
    "from pathlib import Path"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1ce0fafb",
   "metadata": {},
   "outputs": [],
   "source": [
    "def add_to_pipeline(data,name):\n",
    "\n",
    "    # Initialize the pipeline\n",
    "    pipeline = dlt.pipeline(destination=\"postgres\", dataset_name=\"raw_motor_vehicle_collisions\")\n",
    "\n",
    "    # Run the pipeline\n",
    "    load_info = pipeline.run(data,table_name=name, write_disposition=\"append\", loader_file_format=\"csv\")\n",
    "\n",
    "    # Print the load info\n",
    "    print(load_info)\n",
    "    # Print the number of rows loaded"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "34980935",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Pipeline dlt_ipykernel_launcher load step completed in 0.48 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229624.0943716 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.26 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229626.0066736 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.25 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229627.7143981 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.27 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229629.2844894 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.27 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229630.837843 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.28 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229632.4789443 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.30 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229634.121459 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.24 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229635.7181072 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.29 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229637.2978146 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.33 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229638.91567 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.32 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229640.5442724 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.39 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229642.180126 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.29 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229643.8763256 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.30 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229645.4758832 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.39 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229647.0981 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.37 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229648.916681 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 59 minutes and 58.85 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229650.7016752 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.31 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229650.9278097 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.34 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229652.6049724 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.38 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229654.2525337 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.40 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229655.8909476 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.36 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229657.9368994 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.37 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229659.9106252 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.37 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229661.677316 is LOADED and contains no failed jobs\n",
      "Pipeline dlt_ipykernel_launcher load step completed in 0.34 seconds\n",
      "1 load package(s) were loaded to destination postgres and into dataset motor_vehicle_collisions\n",
      "The postgres destination used postgresql://loader:***@localhost:5432/dlt_data location to store data\n",
      "Load package 1748229663.667024 is LOADED and contains no failed jobs\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-26 11:21:07,122|[ERROR]|995|140615677372096|dlt|load.py|w_run_job:247|Transient exception in job transfomed_mvc_crashes.285db8faa3.csv in file /home/ksakra/.dlt/pipelines/dlt_ipykernel_launcher/load/normalized/1748229665.6249466/started_jobs/transfomed_mvc_crashes.285db8faa3.0.csv\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/common/destination/client.py\", line 404, in run_managed\n",
      "    self.run()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/destinations/impl/postgres/postgres.py\", line 133, in run\n",
      "    cursor.copy_expert(copy_sql, f, size=8192)\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type double precision: \"     \"\n",
      "CONTEXT:  COPY transfomed_mvc_crashes, line 17724, column zip_code: \"     \"\n",
      "\n",
      "2025-05-26 11:21:07,974|[WARNING]|995|140617910724416|dlt|load.py|complete_jobs:430|Job for transfomed_mvc_crashes.285db8faa3.csv retried in load 1748229665.6249466 with message invalid input syntax for type double precision: \"     \"\n",
      "CONTEXT:  COPY transfomed_mvc_crashes, line 17724, column zip_code: \"     \"\n",
      "\n",
      "2025-05-26 11:21:08,119|[ERROR]|995|140615677372096|dlt|load.py|w_run_job:247|Transient exception in job transfomed_mvc_crashes.285db8faa3.csv in file /home/ksakra/.dlt/pipelines/dlt_ipykernel_launcher/load/normalized/1748229665.6249466/started_jobs/transfomed_mvc_crashes.285db8faa3.1.csv\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/common/destination/client.py\", line 404, in run_managed\n",
      "    self.run()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/destinations/impl/postgres/postgres.py\", line 133, in run\n",
      "    cursor.copy_expert(copy_sql, f, size=8192)\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type double precision: \"     \"\n",
      "CONTEXT:  COPY transfomed_mvc_crashes, line 17724, column zip_code: \"     \"\n",
      "\n",
      "2025-05-26 11:21:08,978|[WARNING]|995|140617910724416|dlt|load.py|complete_jobs:430|Job for transfomed_mvc_crashes.285db8faa3.csv retried in load 1748229665.6249466 with message invalid input syntax for type double precision: \"     \"\n",
      "CONTEXT:  COPY transfomed_mvc_crashes, line 17724, column zip_code: \"     \"\n",
      "\n",
      "2025-05-26 11:21:09,135|[ERROR]|995|140615677372096|dlt|load.py|w_run_job:247|Transient exception in job transfomed_mvc_crashes.285db8faa3.csv in file /home/ksakra/.dlt/pipelines/dlt_ipykernel_launcher/load/normalized/1748229665.6249466/started_jobs/transfomed_mvc_crashes.285db8faa3.2.csv\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/common/destination/client.py\", line 404, in run_managed\n",
      "    self.run()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/destinations/impl/postgres/postgres.py\", line 133, in run\n",
      "    cursor.copy_expert(copy_sql, f, size=8192)\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type double precision: \"     \"\n",
      "CONTEXT:  COPY transfomed_mvc_crashes, line 17724, column zip_code: \"     \"\n",
      "\n",
      "2025-05-26 11:21:09,984|[WARNING]|995|140617910724416|dlt|load.py|complete_jobs:430|Job for transfomed_mvc_crashes.285db8faa3.csv retried in load 1748229665.6249466 with message invalid input syntax for type double precision: \"     \"\n",
      "CONTEXT:  COPY transfomed_mvc_crashes, line 17724, column zip_code: \"     \"\n",
      "\n",
      "2025-05-26 11:21:10,118|[ERROR]|995|140615677372096|dlt|load.py|w_run_job:247|Transient exception in job transfomed_mvc_crashes.285db8faa3.csv in file /home/ksakra/.dlt/pipelines/dlt_ipykernel_launcher/load/normalized/1748229665.6249466/started_jobs/transfomed_mvc_crashes.285db8faa3.3.csv\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/common/destination/client.py\", line 404, in run_managed\n",
      "    self.run()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/destinations/impl/postgres/postgres.py\", line 133, in run\n",
      "    cursor.copy_expert(copy_sql, f, size=8192)\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type double precision: \"     \"\n",
      "CONTEXT:  COPY transfomed_mvc_crashes, line 17724, column zip_code: \"     \"\n",
      "\n",
      "2025-05-26 11:21:10,987|[WARNING]|995|140617910724416|dlt|load.py|complete_jobs:430|Job for transfomed_mvc_crashes.285db8faa3.csv retried in load 1748229665.6249466 with message invalid input syntax for type double precision: \"     \"\n",
      "CONTEXT:  COPY transfomed_mvc_crashes, line 17724, column zip_code: \"     \"\n",
      "\n",
      "2025-05-26 11:21:11,127|[ERROR]|995|140615677372096|dlt|load.py|w_run_job:247|Transient exception in job transfomed_mvc_crashes.285db8faa3.csv in file /home/ksakra/.dlt/pipelines/dlt_ipykernel_launcher/load/normalized/1748229665.6249466/started_jobs/transfomed_mvc_crashes.285db8faa3.4.csv\n",
      "Traceback (most recent call last):\n",
      "  File \"/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/common/destination/client.py\", line 404, in run_managed\n",
      "    self.run()\n",
      "    ~~~~~~~~^^\n",
      "  File \"/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/destinations/impl/postgres/postgres.py\", line 133, in run\n",
      "    cursor.copy_expert(copy_sql, f, size=8192)\n",
      "    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type double precision: \"     \"\n",
      "CONTEXT:  COPY transfomed_mvc_crashes, line 17724, column zip_code: \"     \"\n",
      "\n",
      "2025-05-26 11:21:11,989|[WARNING]|995|140617910724416|dlt|load.py|complete_jobs:430|Job for transfomed_mvc_crashes.285db8faa3.csv retried in load 1748229665.6249466 with message invalid input syntax for type double precision: \"     \"\n",
      "CONTEXT:  COPY transfomed_mvc_crashes, line 17724, column zip_code: \"     \"\n",
      "\n"
     ]
    },
    {
     "ename": "PipelineStepFailed",
     "evalue": "Pipeline execution failed at stage load when processing package 1748229665.6249466 with exception:\n\n<class 'dlt.load.exceptions.LoadClientJobRetry'>\nJob for transfomed_mvc_crashes.285db8faa3.csv had 5 retries which a multiple of 5. Exiting retry loop. You can still rerun the load package to retry this job. Last failure message was invalid input syntax for type double precision: \"     \"\nCONTEXT:  COPY transfomed_mvc_crashes, line 17724, column zip_code: \"     \"\n",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mLoadClientJobRetry\u001b[39m                        Traceback (most recent call last)",
      "\u001b[36mFile \u001b[39m\u001b[32m/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/pipeline/pipeline.py:591\u001b[39m, in \u001b[36mPipeline.load\u001b[39m\u001b[34m(self, destination, dataset_name, credentials, workers, raise_on_failed_jobs)\u001b[39m\n\u001b[32m    590\u001b[39m \u001b[38;5;28;01mwith\u001b[39;00m signals.delayed_signals():\n\u001b[32m--> \u001b[39m\u001b[32m591\u001b[39m     \u001b[43mrunner\u001b[49m\u001b[43m.\u001b[49m\u001b[43mrun_pool\u001b[49m\u001b[43m(\u001b[49m\u001b[43mload_step\u001b[49m\u001b[43m.\u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mload_step\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    592\u001b[39m info: LoadInfo = \u001b[38;5;28mself\u001b[39m._get_step_info(load_step)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/common/runners/pool_runner.py:91\u001b[39m, in \u001b[36mrun_pool\u001b[39m\u001b[34m(config, run_f)\u001b[39m\n\u001b[32m     90\u001b[39m logger.debug(\u001b[33m\"\u001b[39m\u001b[33mRunning pool\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m---> \u001b[39m\u001b[32m91\u001b[39m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[43m_run_func\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m:\n\u001b[32m     92\u001b[39m     \u001b[38;5;66;03m# for next run\u001b[39;00m\n\u001b[32m     93\u001b[39m     signals.raise_if_signalled()\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/common/runners/pool_runner.py:84\u001b[39m, in \u001b[36mrun_pool.<locals>._run_func\u001b[39m\u001b[34m()\u001b[39m\n\u001b[32m     83\u001b[39m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(run_f, Runnable):\n\u001b[32m---> \u001b[39m\u001b[32m84\u001b[39m     run_metrics = \u001b[43mrun_f\u001b[49m\u001b[43m.\u001b[49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[43mcast\u001b[49m\u001b[43m(\u001b[49m\u001b[43mTExecutor\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mpool\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m     85\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/load/load.py:638\u001b[39m, in \u001b[36mLoad.run\u001b[39m\u001b[34m(self, pool)\u001b[39m\n\u001b[32m    637\u001b[39m             \u001b[38;5;28mself\u001b[39m._step_info_start_load_id(load_id)\n\u001b[32m--> \u001b[39m\u001b[32m638\u001b[39m         \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mload_single_package\u001b[49m\u001b[43m(\u001b[49m\u001b[43mload_id\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mschema\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    640\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m TRunMetrics(\u001b[38;5;28;01mFalse\u001b[39;00m, \u001b[38;5;28mlen\u001b[39m(\u001b[38;5;28mself\u001b[39m.load_storage.list_normalized_packages()))\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/load/load.py:597\u001b[39m, in \u001b[36mLoad.load_single_package\u001b[39m\u001b[34m(self, load_id, schema)\u001b[39m\n\u001b[32m    596\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m pending_exception:\n\u001b[32m--> \u001b[39m\u001b[32m597\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m pending_exception\n\u001b[32m    598\u001b[39m \u001b[38;5;28;01mbreak\u001b[39;00m\n",
      "\u001b[31mLoadClientJobRetry\u001b[39m: Job for transfomed_mvc_crashes.285db8faa3.csv had 5 retries which a multiple of 5. Exiting retry loop. You can still rerun the load package to retry this job. Last failure message was invalid input syntax for type double precision: \"     \"\nCONTEXT:  COPY transfomed_mvc_crashes, line 17724, column zip_code: \"     \"\n",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[31mPipelineStepFailed\u001b[39m                        Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[13]\u001b[39m\u001b[32m, line 8\u001b[39m\n\u001b[32m      6\u001b[39m \u001b[38;5;28;01mfor\u001b[39;00m file \u001b[38;5;129;01min\u001b[39;00m path.glob(\u001b[33m\"\u001b[39m\u001b[33m*.csv\u001b[39m\u001b[33m\"\u001b[39m):\n\u001b[32m      7\u001b[39m     df = pd.read_csv(file)\n\u001b[32m----> \u001b[39m\u001b[32m8\u001b[39m     \u001b[43madd_to_pipeline\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdf\u001b[49m\u001b[43m,\u001b[49m\u001b[43mname\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[2]\u001b[39m\u001b[32m, line 7\u001b[39m, in \u001b[36madd_to_pipeline\u001b[39m\u001b[34m(data, name)\u001b[39m\n\u001b[32m      4\u001b[39m pipeline = dlt.pipeline(destination=\u001b[33m\"\u001b[39m\u001b[33mpostgres\u001b[39m\u001b[33m\"\u001b[39m, dataset_name=\u001b[33m\"\u001b[39m\u001b[33mmotor_vehicle_collisions\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m      6\u001b[39m \u001b[38;5;66;03m# Run the pipeline\u001b[39;00m\n\u001b[32m----> \u001b[39m\u001b[32m7\u001b[39m load_info = \u001b[43mpipeline\u001b[49m\u001b[43m.\u001b[49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdata\u001b[49m\u001b[43m,\u001b[49m\u001b[43mtable_name\u001b[49m\u001b[43m=\u001b[49m\u001b[43mname\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mwrite_disposition\u001b[49m\u001b[43m=\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mappend\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mloader_file_format\u001b[49m\u001b[43m=\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mcsv\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[32m      9\u001b[39m \u001b[38;5;66;03m# Print the load info\u001b[39;00m\n\u001b[32m     10\u001b[39m \u001b[38;5;28mprint\u001b[39m(load_info)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/pipeline/pipeline.py:222\u001b[39m, in \u001b[36mwith_runtime_trace.<locals>.decorator.<locals>._wrap\u001b[39m\u001b[34m(self, *args, **kwargs)\u001b[39m\n\u001b[32m    219\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m trace:\n\u001b[32m    220\u001b[39m         trace_step = start_trace_step(trace, cast(TPipelineStep, f.\u001b[34m__name__\u001b[39m), \u001b[38;5;28mself\u001b[39m)\n\u001b[32m--> \u001b[39m\u001b[32m222\u001b[39m     step_info = \u001b[43mf\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    223\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m step_info\n\u001b[32m    224\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m ex:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/pipeline/pipeline.py:271\u001b[39m, in \u001b[36mwith_config_section.<locals>.decorator.<locals>._wrap\u001b[39m\u001b[34m(self, *args, **kwargs)\u001b[39m\n\u001b[32m    263\u001b[39m \u001b[38;5;129m@wraps\u001b[39m(f)\n\u001b[32m    264\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m_wrap\u001b[39m(\u001b[38;5;28mself\u001b[39m: \u001b[33m\"\u001b[39m\u001b[33mPipeline\u001b[39m\u001b[33m\"\u001b[39m, *args: Any, **kwargs: Any) -> Any:\n\u001b[32m    265\u001b[39m     \u001b[38;5;66;03m# add section context to the container to be used by all configuration without explicit sections resolution\u001b[39;00m\n\u001b[32m    266\u001b[39m     \u001b[38;5;28;01mwith\u001b[39;00m inject_section(\n\u001b[32m    267\u001b[39m         ConfigSectionContext(\n\u001b[32m    268\u001b[39m             pipeline_name=\u001b[38;5;28mself\u001b[39m.pipeline_name, sections=sections, merge_style=merge_func\n\u001b[32m    269\u001b[39m         )\n\u001b[32m    270\u001b[39m     ):\n\u001b[32m--> \u001b[39m\u001b[32m271\u001b[39m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mf\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/pipeline/pipeline.py:731\u001b[39m, in \u001b[36mPipeline.run\u001b[39m\u001b[34m(self, data, destination, staging, dataset_name, credentials, table_name, write_disposition, columns, primary_key, schema, loader_file_format, table_format, schema_contract, refresh)\u001b[39m\n\u001b[32m    718\u001b[39m     \u001b[38;5;28mself\u001b[39m.extract(\n\u001b[32m    719\u001b[39m         data,\n\u001b[32m    720\u001b[39m         table_name=table_name,\n\u001b[32m   (...)\u001b[39m\u001b[32m    728\u001b[39m         loader_file_format=loader_file_format,\n\u001b[32m    729\u001b[39m     )\n\u001b[32m    730\u001b[39m     \u001b[38;5;28mself\u001b[39m.normalize()\n\u001b[32m--> \u001b[39m\u001b[32m731\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mload\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdestination\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mdataset_name\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mcredentials\u001b[49m\u001b[43m=\u001b[49m\u001b[43mcredentials\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    732\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m    733\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/pipeline/pipeline.py:222\u001b[39m, in \u001b[36mwith_runtime_trace.<locals>.decorator.<locals>._wrap\u001b[39m\u001b[34m(self, *args, **kwargs)\u001b[39m\n\u001b[32m    219\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m trace:\n\u001b[32m    220\u001b[39m         trace_step = start_trace_step(trace, cast(TPipelineStep, f.\u001b[34m__name__\u001b[39m), \u001b[38;5;28mself\u001b[39m)\n\u001b[32m--> \u001b[39m\u001b[32m222\u001b[39m     step_info = \u001b[43mf\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    223\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m step_info\n\u001b[32m    224\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m ex:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/pipeline/pipeline.py:162\u001b[39m, in \u001b[36mwith_state_sync.<locals>.decorator.<locals>._wrap\u001b[39m\u001b[34m(self, *args, **kwargs)\u001b[39m\n\u001b[32m    160\u001b[39m should_extract_state = may_extract_state \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;28mself\u001b[39m.config.restore_from_destination\n\u001b[32m    161\u001b[39m \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28mself\u001b[39m.managed_state(extract_state=should_extract_state):\n\u001b[32m--> \u001b[39m\u001b[32m162\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mf\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/pipeline/pipeline.py:271\u001b[39m, in \u001b[36mwith_config_section.<locals>.decorator.<locals>._wrap\u001b[39m\u001b[34m(self, *args, **kwargs)\u001b[39m\n\u001b[32m    263\u001b[39m \u001b[38;5;129m@wraps\u001b[39m(f)\n\u001b[32m    264\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m_wrap\u001b[39m(\u001b[38;5;28mself\u001b[39m: \u001b[33m\"\u001b[39m\u001b[33mPipeline\u001b[39m\u001b[33m\"\u001b[39m, *args: Any, **kwargs: Any) -> Any:\n\u001b[32m    265\u001b[39m     \u001b[38;5;66;03m# add section context to the container to be used by all configuration without explicit sections resolution\u001b[39;00m\n\u001b[32m    266\u001b[39m     \u001b[38;5;28;01mwith\u001b[39;00m inject_section(\n\u001b[32m    267\u001b[39m         ConfigSectionContext(\n\u001b[32m    268\u001b[39m             pipeline_name=\u001b[38;5;28mself\u001b[39m.pipeline_name, sections=sections, merge_style=merge_func\n\u001b[32m    269\u001b[39m         )\n\u001b[32m    270\u001b[39m     ):\n\u001b[32m--> \u001b[39m\u001b[32m271\u001b[39m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mf\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/mnt/d/Projects/Project-1-Motor-Vehicle-Collisions-/.venv/lib/python3.13/site-packages/dlt/pipeline/pipeline.py:598\u001b[39m, in \u001b[36mPipeline.load\u001b[39m\u001b[34m(self, destination, dataset_name, credentials, workers, raise_on_failed_jobs)\u001b[39m\n\u001b[32m    596\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m l_ex:\n\u001b[32m    597\u001b[39m     step_info = \u001b[38;5;28mself\u001b[39m._get_step_info(load_step)\n\u001b[32m--> \u001b[39m\u001b[32m598\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m PipelineStepFailed(\n\u001b[32m    599\u001b[39m         \u001b[38;5;28mself\u001b[39m, \u001b[33m\"\u001b[39m\u001b[33mload\u001b[39m\u001b[33m\"\u001b[39m, load_step.current_load_id, l_ex, step_info\n\u001b[32m    600\u001b[39m     ) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01ml_ex\u001b[39;00m\n",
      "\u001b[31mPipelineStepFailed\u001b[39m: Pipeline execution failed at stage load when processing package 1748229665.6249466 with exception:\n\n<class 'dlt.load.exceptions.LoadClientJobRetry'>\nJob for transfomed_mvc_crashes.285db8faa3.csv had 5 retries which a multiple of 5. Exiting retry loop. You can still rerun the load package to retry this job. Last failure message was invalid input syntax for type double precision: \"     \"\nCONTEXT:  COPY transfomed_mvc_crashes, line 17724, column zip_code: \"     \"\n"
     ]
    }
   ],
   "source": [
    "path = Path('./data/transformed')\n",
    "for roots,dirs,file in path.walk(on_error=print):\n",
    "    for dir in dirs:\n",
    "        path = Path(roots) / dir\n",
    "        name = f\"transfomed_{dir}\"\n",
    "        for file in path.glob(\"*.csv\"):\n",
    "            df = pd.read_csv(file)\n",
    "            add_to_pipeline(df,name)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a2103a4a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6a99fb36",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "36846cc9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
